---
extends: default
rules:
  line-length:
    max: 120
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  truthy:
    allowed-values:
      - 'true'
      - 'yes'
      - 'false'
      - 'no'
