---
- name: Create SSH directory for root
  file:
    path: /root/.ssh/
    state: directory
    mode: 0700

- name: Create root SSH key pair for PVE
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 521
    ssh_key_file: /root/.ssh/id_ed25519
    ssh_key_type: ed25519
    ssh_key_comment: "root@{{ inventory_hostname_short }}"

- name: Fetch root SSH public key
  slurp:
    src: /root/.ssh/id_ed25519.pub
  register: _proxmox_root_ssh_pubkey

- name: Authorize all hosts' root SSH public keys
  authorized_key:
    user: root
    key: "{{ hostvars[item]._proxmox_root_ssh_pubkey.content | b64decode }}"
  with_items: "{{ groups[pve_group] }}"

- name: Configure SSH clients for connecting to PVE cluster hosts
  blockinfile:
    dest: /etc/ssh/ssh_config
    create: yes
    marker: "# {mark}: PVE host configuration options (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      Host {{ hostvars[host].pve_cluster_ssh_addrs | join(" ") }}
          IdentityFile /root/.ssh/id_ed25519
          Port {{ pve_ssh_port }}
      {% endfor %}

- name: Allow root logins from PVE cluster hosts
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark}: Allow root logins from PVE hosts (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      Match Address {{ hostvars[host].pve_cluster_ssh_addrs | join(",") }}
      PermitRootLogin prohibit-password
      {% endfor %}
    validate: "/usr/sbin/sshd -t -f %s"
  notify:
    - reload sshd configuration

- name: Fetch SSH public host keys
  slurp:
    src: "/etc/ssh/{{ item }}"
  register: proxmox_ssh_public_host_keys
  with_items:
    - ssh_host_rsa_key.pub
    - ssh_host_ed25519_key.pub
    - ssh_host_ecdsa_key.pub

- name: Check status of known hosts file
  stat:
    path: /etc/ssh/ssh_known_hosts
  register: _pve_known_hosts_file

- name: Add every host's host keys to global known_hosts
  blockinfile:
    dest: /etc/ssh/ssh_known_hosts
    create: yes
    marker: "# {mark}: PVE host keys (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      {% for _key_slurp in hostvars[host].proxmox_ssh_public_host_keys.results %}
      {%- set _key = ' '.join((_key_slurp.content | b64decode).split()[:-1]) -%}
      {{ hostvars[host].pve_cluster_ssh_addrs | join(",") }} {{ _key }}
      {% endfor %}
      {% endfor %}
  when:
    - "not (_pve_known_hosts_file.stat.islnk is defined and _pve_known_hosts_file.stat.islnk)"

- name: Add PVE-provided ciphers to SSH client config
  lineinfile:
    line: "Ciphers {{ pve_ssh_ciphers }}"
    regexp: "^Ciphers .*"
    insertbefore: BOF
    create: yes
    dest: /root/.ssh/config
